name: Debug Workflow

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Display IP Address
        run: |
          curl ifconfig.me
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-server
      - name: Start SSH service
        run: sudo service ssh start
      - name: Add SSH private key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Debugging Step
        run: |
          # Insert any commands you want to run for debugging here
          echo "Debugging..."
          sleep 120  # Example: sleep for 2 minutes
      - name: End of Workflow
        run: |
          echo "End of Workflow"
